const express = require('express');
const axios = require('axios');
const app = express();

app.use(express.json());

// Airtable Configuration
const AIRTABLE_API_KEY = process.env.AIRTABLE_API_KEY; // Set in environment variables
const AIRTABLE_BASE_ID = process.env.AIRTABLE_BASE_ID; // Set in environment variables
const AIRTABLE_TABLE_NAME = 'Prices';

app.post('/webhook', async (req, res) => {
    try {
        // 1. Extract session parameters from Dialogflow CX request body
        const parameters = req.body.sessionInfo?.parameters || {};
        const product = parameters.product;
        const unit = parameters.unit; // New grocery unit parameter (e.g., 2kg, 1 loaf, 2L)
        const city = parameters.city;
        const subLocation = parameters.sub_location;
        const brand = parameters.brand || 'any';

        // 2. Construct Airtable Filter Formula (includes {Unit} column match)
        let filterFormula = `AND({Product} = '${product}', {Unit} = '${unit}', {City} = '${city}', {Sub_Location} = '${subLocation}')`;
        
        if (brand && brand.toLowerCase() !== 'any') {
            filterFormula = `AND({Product} = '${product}', {Unit} = '${unit}', {City} = '${city}', {Sub_Location} = '${subLocation}', {Brand} = '${brand}')`;
        }

        // 3. Query Airtable API (Sorting by lowest price)
        const airtableUrl = `https://api.airtable.com/v0/${AIRTABLE_BASE_ID}/${encodeURIComponent(AIRTABLE_TABLE_NAME)}?filterByFormula=${encodeURIComponent(filterFormula)}&sort[0][field]=Price&sort[0][direction]=asc`;
        
        const airtableResponse = await axios.get(airtableUrl, {
            headers: { Authorization: `Bearer ${AIRTABLE_API_KEY}` }
        });

        const records = airtableResponse.data.records;

        // Variables for final response
        let priceResultsText = "";
        let searchTimestamp = "";

        // 4. Format Price Results and extract Airtable Formatted_Timestamp
        if (records.length === 0) {
            priceResultsText = `❌ Sorry, no live in-stock prices found for **${product} (${unit})** in ${subLocation}, ${city}.`;
            
            // Fallback timestamp if no matching record is found in Airtable
            searchTimestamp = new Date().toLocaleString("en-GB", { timeZone: "Africa/Harare" }).replace(',', '');
        } else {
            const medals = ['🥇', '🥈', '🥉'];
            
            // Extract the timestamp generated by your Airtable formula field from the top record
            const airtableTime = records[0].fields.Formatted_Timestamp || records[0].fields['Formatted Timestamp'];

            if (airtableTime) {
                searchTimestamp = airtableTime;
            } else {
                // Server fallback timestamp in Harare time
                searchTimestamp = new Date().toLocaleString("en-GB", { 
                    timeZone: "Africa/Harare",
                    day: "2-digit", 
                    month: "2-digit", 
                    year: "2-digit", 
                    hour: "2-digit", 
                    minute: "2-digit", 
                    second: "2-digit" 
                }).replace(',', '');
            }

            const formattedList = records.map((record, index) => {
                const store = record.fields.Store_Name || 'Local Store';
                const price = record.fields.Price ? `$${record.fields.Price.toFixed(2)}` : 'N/A';
                const prefix = medals[index] || '•';
                const note = index === 0 ? ' (Cheapest! 🎉)' : '';
                return `${prefix} **${store}:** ${price}${note}`;
            }).join('\n');

            priceResultsText = formattedList;
        }

        // 5. Return Payload back to Dialogflow CX
        return res.json({
            sessionInfo: {
                parameters: {
                    price_results_list: priceResultsText,
                    search_timestamp: searchTimestamp
                }
            }
        });

    } catch (error) {
        console.error('Webhook Error:', error.message);
        
        const errorTimestamp = new Date().toLocaleString("en-GB", { timeZone: "Africa/Harare" }).replace(',', '');

        return res.json({
            sessionInfo: {
                parameters: {
                    price_results_list: "⚠️ Unable to retrieve prices at the moment. Please try again later.",
                    search_timestamp: errorTimestamp
                }
            }
        });
    }
});

// Start Server
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
    console.log(`PriceCheckZim Webhook server running on port ${PORT}`);
});


      
            
           
                

   
