const express = require('express');
const axios = require('axios');
const app = express();

app.use(express.json());

// Airtable Configuration
const AIRTABLE_API_KEY = process.env.AIRTABLE_API_KEY; // Set in environment variables
const AIRTABLE_BASE_ID = process.env.AIRTABLE_BASE_ID; // Set in environment variables
const AIRTABLE_TABLE_NAME = 'Prices';

app.post('/webhook', async (req, res) => {
    try {
        // 1. Extract session parameters from Dialogflow CX request body
        const parameters = req.body.sessionInfo?.parameters || {};
        const product = parameters.product;
        const city = parameters.city;
        const subLocation = parameters.sub_location;
        const brand = parameters.brand || 'any';

        // 2. Construct Airtable Filter Formula
        let filterFormula = `AND({Product} = '${product}', {City} = '${city}', {Sub_Location} = '${subLocation}')`;
        if (brand && brand.toLowerCase() !== 'any') {
            filterFormula = `AND({Product} = '${product}', {City} = '${city}', {Sub_Location} = '${subLocation}', {Brand} = '${brand}')`;
        }

        // 3. Query Airtable API (Sorting by lowest price)
        const airtableUrl = `https://api.airtable.com/v0/${AIRTABLE_BASE_ID}/${encodeURIComponent(AIRTABLE_TABLE_NAME)}?filterByFormula=${encodeURIComponent(filterFormula)}&sort[0][field]=Price&sort[0][direction]=asc`;
        
        const airtableResponse = await axios.get(airtableUrl, {
            headers: { Authorization: `Bearer ${AIRTABLE_API_KEY}` }
        });

        const records = airtableResponse.data.records;

        // Variables for final response
        let priceResultsText = "";
        let searchTimestamp = "";

        // 4. Format Price Results and extract Airtable Formatted_Timestamp
        if (records.length === 0) {
            priceResultsText = `❌ Sorry, no live in-stock prices found for **${product}** in ${subLocation}, ${city}.`;
            
            // Fallback timestamp if no record is found in Airtable
            searchTimestamp = new Date().toLocaleString("en-GB", { timeZone: "Africa/Harare" }).replace(',', '');
        } else {
            const medals = ['🥇', '🥈', '🥉'];
            
            // Extract the timestamp generated by your Airtable formula field from the top record
            searchTimestamp = records[0].fields.Formatted_Timestamp || '';

            const formattedList = records.map((record, index) => {
                const store = record.fields.Store_Name || 'Local Store';
                const price = record.fields.Price ? `$${record.fields.Price.toFixed(2)}` : 'N/A';
                const prefix = medals[index] || '•';
                const note = index === 0 ? ' (Cheapest! 🎉)' : '';
                return `${prefix} **${store}:** ${price}${note}`;
            }).join('\n');

            priceResultsText = formattedList;
        }

        // 5. Return Payload back to Dialogflow CX
        return res.json({
            sessionInfo: {
                parameters: {
                    price_results_list: priceResultsText,
                    search_timestamp: searchTimestamp
                }
            }
        });

    } catch (error) {
        console.error('Webhook Error:', error.message);
        
        return res.json({
            sessionInfo: {
                parameters: {
                    price_results_list: "⚠️ Unable to retrieve prices at the moment. Please try again later.",
                    search_timestamp: ""
                }
            }
        });
    }
});

// Start Server
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
    console.log(`PriceCheckZim Webhook server running on port ${PORT}`);
});

 

    
      
      
